spring:

  data:
    mongodb:
      uri: mongodb://localhost:27017/chat

  security:
    jwt:
      uri: /auth/**
      header: Authorization
      prefix: Bearer
      expiration: 86400
      secret: JwtSecretKey